### PR TITLE
Switch to new API endpoints

### PR DESCRIPTION
**Pull request by EtienneMD**
This will fix the add-on to use the latest supervisor api, fixes a few typos and optimizes the Dockerfile.

### CODE REVIEW

**Comment by d0ugal** [comment]
Thanks!

**Comment by EtienneMD** [comment]
My pleasure.

You will need to trigger a new build in order for the update to be available to all users.

**Comment by d0ugal** [comment]
Yup, I’ll try and do that. Embarrassingly I need to try and remember the process 😆

**Comment by EtienneMD** [comment]
If that fails we can have the image be built locally for every user. While not ideal, it'd be a lot easier for you

**Comment by d0ugal** [comment]
Can you share how you built it? Last time I worked on this I was using 

https://github.com/hassio-addons/build-env

However, it seems to have stopped working and that project is no longer deprecated.

The helper commands that I had written fail.

`tox -e docker-build` or `./scripts/docker-build.sh $PWD`

**Comment by d0ugal** [comment]
I am attempting to add the Github actions to this repo. https://github.com/home-assistant/builder

**Comment by EtienneMD** [comment]
I built locally on my instance using the store. I guess they switched to using GitHub actions for their builds. See [here](https://github.com/home-assistant/builder).

I have to go to work for a few days so will not be able to look into it. 

If all else fails just remove the image line in config.json and it will build locally for everybody.

**Comment by d0ugal** [comment]
I have managed to make a release! I tried the github actions and failed but I did manage to get my old build scripts working with the new builder.

https://github.com/d0ugal/hassio-dropbox-upload/commit/880f37e9c4dc3a3a4342919e88e282f6bd9b26bc

Since the github actions use the same builder it should be easy to mover over but I have not quite figured that bit out yet.

**Comment by EtienneMD** [comment]
Working on my end, nice work. 

Thank for taking the time to work on this even though you have stopped using it. Really appreciated. 

Cheers!

**Comment by d0ugal** [comment]
For some reason I see 1.3.0 on docker hub but I only see 1.2.11 in my ha install. I only just added the repository... maybe something is just cached? anyway that is all the time I have for now, hopefully helps some people out!

**Comment by d0ugal** [comment]
Nevermind, I see 1.3.0 - I guess I might as well try it out now :sweat_smile:

**Pull request merged**
